#include "../include/testbench.hpp"
#include "Vtop_level.h"
#include <cstdint>
#include <iostream>
#include <vector>
#include <iomanip>
#include <map>

int main(int argc, char **argv)
{
    Testbench<Vtop_level> tb("trace_top_level_stress.vcd");

    std::cout << "\n==> Top Level Integration: Architectural Stress Test\n"
              << std::endl;

    // ====================================================
    // 1. Assembly Workload: Loop and Branch Validation
    // ====================================================
    // 0x00: ADDI x1, x0, 16      ; x1 = 16 (Array Base Pointer)
    // 0x04: ADDI x2, x0, 5       ; x2 = 5  (Loop Counter)
    // 0x08: ADD  x3, x0, x0      ; x3 = 0  (Sum Accumulator)
    // --- Loop Start ---
    // 0x0C: SW   x2, 0(x1)       ; Mem[x1] = x2 (Store current counter to array)
    // 0x10: ADD  x3, x3, x2      ; x3 = x3 + x2 (Accumulate sum)
    // 0x14: ADDI x1, x1, 4       ; x1 = x1 + 4  (Increment base pointer)
    // 0x18: ADDI x2, x2, -1      ; x2 = x2 - 1  (Decrement loop counter)
    // 0x1C: BNE  x2, x0, -16     ; If x2 != 0, Branch to 0x0C
    // --- Loop End ---
    // 0x20: LUI  x4, 0x12345     ; x4 = 0x12345000 (U-Type ALU validation)
    // 0x24: JAL  x5, 8           ; Jump to 0x2C (Save return address 0x28 in x5)
    // 0x28: NOP                  ; Skipped Instruction (Test fails if executed)
    // --- Jump Target ---
    // 0x2C: SW   x3, 64(x0)      ; Mem[64] = x3 (Store final accumulated sum: 15)
    // 0x30: JAL  x0, 0           ; Infinite Loop (Halt execution)

    std::vector<uint32_t> rom = {
        0x01000093, // 0x00
        0x00500113, // 0x04
        0x000001B3, // 0x08
        0x0020A023, // 0x0C
        0x002181B3, // 0x10
        0x00408093, // 0x14
        0xFFF10113, // 0x18
        0xFE0118E3, // 0x1C
        0x12345237, // 0x20
        0x008002EF, // 0x24
        0x00000013, // 0x28
        0x04302023, // 0x2C
        0x0000006F  // 0x30
    };

    tb.reset();

    int max_cycles = 45;               // Expected completion in ~30 cycles
    std::map<uint32_t, uint32_t> dmem; // Software model of Data Memory
    bool program_finished = false;

    for (int cycle = 0; cycle < max_cycles; cycle++)
    {
        uint32_t pc_word_addr = tb.dut->imem_addr_o / 4;

        if (pc_word_addr < rom.size())
        {
            tb.dut->imem_rdata_i = rom[pc_word_addr];
        }
        else
        {
            tb.dut->imem_rdata_i = 0x00000013; // Default to NOP
        }

        tb.eval();

        // Monitor processor write requests to Data Memory
        if (tb.dut->dmem_we_o)
        {
            uint32_t addr = tb.dut->dmem_addr_o;
            uint32_t data = tb.dut->dmem_wdata_o;
            dmem[addr] = data; // Persist data in the software model

            // Detecting a write to address 64 indicates successful loop completion
            // and correct execution of the JAL instruction.
            if (addr == 64)
            {
                program_finished = true;
                std::cout << "--- Execution completion detected at cycle " << cycle << " ---\n";
                break;
            }
        }

        tb.tick();
    }

    // ====================================================
    // HARDWARE VALIDATION ASSERTIONS
    // ====================================================
    CHECK_EQ(true, program_finished, "CPU successfully completed the loop and final jump (SW at addr 64)");

    std::cout << "\n--- Memory Array Verification (Generated by BNE Loop) ---\n";
    CHECK_EQ(5, dmem[16], "Array[0]: Mem[16] == 5");
    CHECK_EQ(4, dmem[20], "Array[1]: Mem[20] == 4");
    CHECK_EQ(3, dmem[24], "Array[2]: Mem[24] == 3");
    CHECK_EQ(2, dmem[28], "Array[3]: Mem[28] == 2");
    CHECK_EQ(1, dmem[32], "Array[4]: Mem[32] == 1");

    std::cout << "\n--- Accumulator Verification (Final Sum) ---\n";
    CHECK_EQ(15, dmem[64], "Final result at Mem[64] contains the exact sum (15)");

    std::cout << "\n✅ Top Level Stress Test PASSED: Complex control flow and memory operations verified.\n"
              << std::endl;
    return 0;
}