/*

    PROJECT: SuperNova-RV
    MODULE: SuperNova Package (supernova_pkg)
    DESCRIPTION: Global package containing type definitions, enums, and constants shared across the entire processor architecture.

    AUTHOR: André Solano Ferreira Rodrigues Maiolini
    DATE:   2026-05-01

*/

package supernova_pkg;

  // ==========================================================================
  // ALU Operation Codes (ALU Control Signals)
  // ==========================================================================

  // Definition of ALU operation codes using strong typing (enum)
  // Names in PascalCase to follow Verible Linter rules

  typedef enum logic [3:0] {

    AluAdd  = 4'b0000,
    AluSub  = 4'b1000,
    AluSll  = 4'b0001,
    AluSlt  = 4'b0010,
    AluSltu = 4'b0011,
    AluXor  = 4'b0100,
    AluSrl  = 4'b0101,
    AluSra  = 4'b1101,
    AluOr   = 4'b0110,
    AluAnd  = 4'b0111

  } alu_op_e;

  // ==========================================================================
  // Immediate Types for the Immediate Generator (ImmGen)
  // ==========================================================================

  // Definition of Immediate formats using strong typing (enum)
  // Names in PascalCase to follow Verible Linter rules

  typedef enum logic [2:0] {

    ImmI = 3'b000,
    ImmS = 3'b001,
    ImmB = 3'b010,
    ImmU = 3'b011,
    ImmJ = 3'b100

  } imm_type_e;

  // ==========================================================================
  // Memory Access Sizes for the Load Store Unit (LSU)
  // ==========================================================================

  // Definition of Memory Access Sizes

  typedef enum logic [1:0] {
    MemSizeByte = 2'b00,  // lb, lbu, sb
    MemSizeHalf = 2'b01,  // lh, lhu, sh
    MemSizeWord = 2'b10   // lw, sw
  } mem_size_e;

  // ==========================================================================
  //  RISC-V RV32I Opcodes
  // ==========================================================================

  typedef enum logic [6:0] {
    OpcodeLoad   = 7'b0000011, // lw, lh, lb...
    OpcodeImm    = 7'b0010011, // addi, andi...
    OpcodeAuipc  = 7'b0010111, // auipc
    OpcodeStore  = 7'b0100011, // sw, sh, sb
    OpcodeRType  = 7'b0110011, // add, sub, and...
    OpcodeLui    = 7'b0110111, // lui
    OpcodeBranch = 7'b1100011, // beq, bne...
    OpcodeJalr   = 7'b1100111, // jalr
    OpcodeJal    = 7'b1101111  // jal
  } opcode_e;

  // ==========================================================================
  // Control Unit Enums (Mux Selectors and Enables)
  // ==========================================================================

  // ALU Mux A Selector:
  // Choose between rs1, PC, or zero for the first ALU operand

  typedef enum logic [1:0] {
    AluSrcARs1  = 2'b00,  // rs1 register
    AluSrcAPc   = 2'b01,  // Program Counter (AUIPC, JAL)
    AluSrcAZero = 2'b10   // Zero (LUI)
  } alu_src_a_e;

  // ALU Mux B Selector:
  // Choose between rs2 or immediate for the second ALU operand

  typedef enum logic {
    AluSrcBRs2 = 1'b0,  // rs2 register
    AluSrcBImm = 1'b1   // Immediate (Generated by ImmGen)
  } alu_src_b_e;

  // Write-Back Mux Selector (What goes back to the Register File)
  typedef enum logic [1:0] {
    WbSrcAlu = 2'b00,  // ALU result
    WbSrcMem = 2'b01,  // Memor y read (LSU)
    WbSrcPc  = 2'b10   // PC + 4 (Used to save return address in Jumps)
  } wb_src_e;

  // ==========================================================================
  // Pipeline Control Bus (Agrupa os Enums do Nebula)
  // ==========================================================================

  typedef struct packed {

    logic       reg_we;
    wb_src_e    wb_src;
    mem_size_e  mem_size;
    logic       mem_we;
    logic       mem_unsigned;
    alu_src_a_e alu_src_a;
    alu_src_b_e alu_src_b;
    alu_op_e    alu_op;
    logic       jalr_sel;
    logic       is_branch;
    logic       is_jump;

  } ctrl_bus_t;

  // ==========================================================================
  // Estruturas de Barreira do Pipeline (Protostar)
  // ==========================================================================

  // 1. Fetch -> Decode
  typedef struct packed {

    logic [31:0] pc;
    logic [31:0] pc_plus_4;
    logic [31:0] instr;

    // There's no control bus here because the signals are generated in the Decode stage, so they don't exist yet!

  } if_id_t;

  // 2. Decode -> Execute
  typedef struct packed {

    logic [31:0] pc;
    logic [31:0] pc_plus_4;
    logic [31:0] rs1_data;
    logic [31:0] rs2_data;
    logic [31:0] imm;
    logic [4:0]  rs1_addr;   // It's useful for the future Forwarding Unit
    logic [4:0]  rs2_addr;   // It's useful for the future Forwarding Unit
    logic [4:0]  rd_addr;

    // Funct3 for the Branch Unit to decide the type of comparison (beq, bne, blt, etc.)
    logic [2:0] funct3;

    // The control signals are generated in the Decode stage and need to be passed to the Execute stage
    ctrl_bus_t ctrl;

  } id_ex_t;

  // 3. Execute -> Memory
  typedef struct packed {

    logic [31:0] alu_result;
    logic [31:0] rs2_data;
    logic [31:0] pc_plus_4;
    logic [4:0]  rd_addr;

    // The control signals go together with the data to the next stage, so we don't lose them!
    ctrl_bus_t ctrl;

  } ex_mem_t;

  // 4. Memory -> Writeback
  typedef struct packed {

    logic [31:0] alu_result;
    logic [31:0] lsu_rdata;
    logic [31:0] pc_plus_4;
    logic [4:0]  rd_addr;

    // The last stage still needs the control signals to know what to write back!
    ctrl_bus_t ctrl;

  } mem_wb_t;

endpackage
